### ISSUE TITLE
Function 2 documentation (update_grades.py)

### ISSUE THREAD

**Issue by shlrley** [UBC-MDS/gradecalculatorpy#1]
[MS1] Write the documentation for function 2: update_grades.py.

- Assigned to Shirley Zhang 
- Due Friday, January 13, 2023 @ 9 PM PST 

** Remember to create a branch and add useful commit messages! 

- [x] Done
- [x] Have pull request approved

**Comment by CChCheChen** [comment]
Hi @shlrley I reviewed the PR and approved to merge to main branch
