### ISSUE TITLE
the extra optional function

### ISSUE THREAD

**Issue by yukunzGIT** [UBC-MDS/gradecalculatorpy#11]
The extra optional function should be deleted now and we can add it back if we need it later. 

calculate_grade: 
When all course components are presented, calculate the course overall grade based on information provided.

- [x] @CChCheChen added the function and corresponding doctring for milestone1.
- [x] Merge the changes to main branch after approving pull request

**Comment by yukunzGIT** [comment]
Please review the README

**Comment by CChCheChen** [comment]
Function python file created and docstring added
