### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/gradecalculatorpy#22]
Congrats on finishing Milestone 1! We can see that you put some thought into this project. Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

- [x] There isn't an issue by function in the package - mechanics -2

Great job group 20! Overall you did a great job for milestone 1. The project structure was done correctly, and I appreciate how the branches were short concise and each had purpose.

**Comment by CChCheChen** [comment]
Hi @andytai7, much appreciated for you effort to grade our milestone 1.

Not sure what "There isn't an issue by function in the package" actually means, we indeed created issues to track each function which are listed below:
[Function 1 construct course](https://github.com/UBC-MDS/gradecalculatorpy/issues/5)
[Function 2 update grades](https://github.com/UBC-MDS/gradecalculatorpy/issues/1)
[Function 3 predict final](https://github.com/UBC-MDS/gradecalculatorpy/issues/9)
[Extra function 4 calculate grade](https://github.com/UBC-MDS/gradecalculatorpy/issues/11)

Please kindly advice if these are the issues you were looking for.

Best regards,
Chen

**Comment by andytai7** [comment]
Hi @CChCheChen all of these functions have different names, and different formats. It is very hard to distinguish which function is for what. Please write them in a standardized format, so it is easy for one to follow the workflow.
