### ISSUE TITLE
test_calculate_grade.py issues has NO test for the calculate_grade()

### ISSUE THREAD

**Issue by yukunzGIT** [UBC-MDS/gradecalculatorpy#29]
test_calculate_grade.py has NO test for the calculate_grade() function. Chen, you only tested for the properties of the input data frame. 

We should also test for OUTPUT of the calculate_grade() function.

**Comment by CChCheChen** [comment]
Test case for running calculate_grade() added per [here](https://github.com/UBC-MDS/gradecalculatorpy/pull/31/commits/e98959da0415b460644b1e37c767db6aecd7d9c7)
